### ISSUE TITLE
Hitting an error dialog when starting spoke on windows in admin cmd

### ISSUE THREAD

**Issue by gfodor** [MozillaReality/Spoke#149]
Getting this error:

```
Starting spoke-test-cli server...
Serving project directory: parthenon
Server listening on port 9090
(node:26548) UnhandledPromiseRejectionWarning: Error: Exited with code 1
    at ChildProcess.cp.once.code (C:\Users\Gregory Fodor\AppData\Roaming\npm\node_modules\spoke-test-cli\node_modules\opn\index.js:84:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:599:12)
(node:26548) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26548) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Also a modal pops up too, attached.

![image](https://user-images.githubusercontent.com/220020/43931743-01373d8c-9bf5-11e8-8ee8-444d63970752.png)

**Comment by brianpeiris** [comment]
I tried reproing this by running `npm build; node bin\spoke foobar` but that works for me. I think we can put this aside for now at least, since we will probably release v1 as a packaged app.
