### ISSUE TITLE
nav mesh generation fails with server error 500

### ISSUE THREAD

**Issue by arpu** [MozillaReality/Spoke#209]
rcBuildRegions: Region ID overflow
buildNavigation: Could not build watershed regions.

  Error: Invalid objMesh line "Build Failed"
      at objMesh.split.reduce.navPosition (/home/arpu/Work/githubsources/Spoke/src/server/index.js:289:17)
      at Array.reduce (<anonymous>)
      at /home/arpu/Work/githubsources/Spoke/src/server/index.js:275:58
      at Generator.next (<anonymous>)
      at step (/home/arpu/Work/githubsources/Spoke/src/server/index.js:159:191)
      at /home/arpu/Work/githubsources/Spoke/src/server/index.js:159:361
      at <anonymous>

**Comment by brianpeiris** [comment]
Thanks for the report and the example glb. Our nav mesh settings didn't work well for large scenes. Should work now!
